baseurl = "http://www.example.com"
title = "stats.gender-gap.jp"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "stats.gender-gap.jp Admin"
  info = "Full Stack DevOps and Magician"
  description = "John Doe's personal website"
  keywords = "stats,gender,gap"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/images/gender-gap-favicon.svg"
  favicon_32 = "/images/gender-gap-favicon-32x32.png"
  favicon_16 = "/images/gender-gap-favicon-16x16.png"

  since = 2023 

  enableTwemoji = true

  colorScheme = "light"
  hidecolorschemetoggle = true

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/johndoe/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/johndoe/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "ğŸ“Home"
  weight = 1
  url  = "/"
[[menu.main]]
  name = "ğŸšªAbout"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "ğŸ“ƒData source"
  weight = 3
  url = "source/"
[[menu.main]]
  name = "ğŸŒˆAction"
  weight = 4
  url = "action/"
[[menu.main]]
  name = "ğŸ“®Contact"
  weight = 4
  url = "contact/"
