baseurl = "https://fluffy-kulfi-c275a8.netlify.app/"
title = "stats.gender-gap.jp"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "stats.gender-gap.jp Admin"
  info = "Stats of gender-gap JP"
  description = "Stats of gender-gap JP"
  images = ['images/gender-gap-ogp.jpg']
  keywords = "stats,gender,gap,jp"
  avatarurl = "images/avatar.jpg"

  faviconSVG = "/images/gender-gap-favicon.svg"
  favicon_32 = "/images/gender-gap-favicon-32x32.png"
  favicon_16 = "/images/gender-gap-favicon-16x16.png"

  since = 2023 

  enableTwemoji = true

  colorScheme = "light"
  hidecolorschemetoggle = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menu links
[[menu.main]]
  name = "ğŸ“ŠHome"
  weight = 1
  url  = "/"
[[menu.main]]
  name = "ğŸšªAbout"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "ğŸ“Updates"
  weight = 3 
  url = "updates/"
[[menu.main]]
  name = "ğŸ“ƒData source"
  weight = 4 
  url = "source/"
[[menu.main]]
  name = "ğŸŒˆAction"
  weight = 5
  url = "action/"
[[menu.main]]
  name = "ğŸ“®Contact"
  weight = 6
  url = "https://docs.google.com/forms/d/e/1FAIpQLSdv7u_pG63IgZkLBH09SmNOoJ9VfIWQhMM5j2K6denEe92D-Q/viewform"
